name: CI

on:
  pull_request:
    branches:
      - main
    paths:
      - .cargo/**
      - src/**
      - Cargo.lock
      - Cargo.toml
      - .github/workflows/ci.yml

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          target: wasm32-wasi

      - name: Build project
        run: cargo build
